---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Pi hole:
        icon: pi-hole
        href: https://pi-hole.homelab.local
        description: DNS Server
    - Adguard Home:
        icon: adguard-home
        href: https://adguard.homelab.local
        description: DNS Filter
    - Uptime Kuma:
        icon: uptime-kuma
        href: https://uptime-kuma.homelab.local
        description: Monitoring Dashboard
- Docker:
    - Dozzle:
        icon: dozzle
        href: https://dozzle.homelab.local
        description: Docker Logs Dashboard
        container: dozzle
    - Portainer:
        icon: portainer
        href: "https://192.168.0.110:9443"
        description: Docker management tool
        server: my-docker
        container: portainer

- Apps:
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: https://speedtest-tracker.homelab.local
        description: Test internet speed
        server: my-docker
        container: speedtest-tracker
    - Memos:
        icon: memos
        href: https://memos.homelab.local
        description: Simple note taking app
        server: my-docker
        container: memos
    - Jellyfin:
        icon: jellyfin
        href: https://jellyfin.homelab.local
        description: Media server
        server: my-docker
        container: jellyfin
    - Immich:
        icon: immich
        href: https://immich.homelab.local
        description: Immich server
        server: my-docker
        container: immich_server
    - Navidrome:
        icon: navidrome
        href: https://navidrome.homelab.local
        description: Navidrome server
        server: my-docker
        container: navidrome
