---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab
background:
  image: https://images.unsplash.com/photo-1533563906091-fdfdffc3e3c4?q=80&w=1170&auto=format&fit=crop
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 60 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 60 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
layout:
  Infrastructure:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 4
